### ISSUE TITLE
Private applications cannot request a Request Token

### ISSUE THREAD

**Issue by simesy** [XeroAPI/xero-node-sample-app#5]
I have this config which is working on a custom app:
```
{
    "appType": "private",
    "consumerKey": "AAA",
    "consumerSecret": "BBB",
    "privateKeyPath": "../path/to/key.pem",
    "callbackUrl": "http://localhost:3100/access"
}
```

I'm getting 
```
listening on http://localhost:3100
(node:85957) UnhandledPromiseRejectionWarning: Error: XeroError: consumer_key_rejected (Private applications cannot request a Request Token)
    at new XeroError (/REDACTED/test-xero-app/xero-node-sample-app/node_modules/xero-node/lib/XeroError.js:30:24)
    at /REDACTEDtest-xero-app/xero-node-sample-app/node_modules/xero-node/lib/internals/OAuth1HttpClient.js:71:57
    at /REDACTED/test-xero-app/xero-node-sample-app/node_modules/oauth/lib/oauth.js:543:17
    at passBackControl (/REDACTED/test-xero-app/xero-node-sample-app/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/REDACTED/test-xero-app/xero-node-sample-app/node_modules/oauth/lib/oauth.js:409:9)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1098:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
(node:85957) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:85957) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by SidneyAllen** [comment]
@simesy - Private apps don't use 3 legged oauth and therefore won't need a callback URL or need to make a request token call.

Private apps use 2 legged oauth where your consumer key and consumer key ARE you oauth token and oauth token secret and are long lived.  No need for the "oauth dance".
